// AUTO-GENERATED by scripts/sync-sdk-versions.mjs — do not edit by hand.
// Mirrors the Web/Node/RN _version.* codegen pattern: a single bundle
// constant for the SDK identifier sent on every request envelope, kept
// in lockstep with the root SDK manifest. Editing this manually risks
// the wire-format `sdk` field falling out of sync with the artefact's
// published version, which makes server-side debugging impossible.

import Foundation

public enum SDK {
    public static let name = "@cross-deck/swift"
    public static let version = "1.7.2"
}
